before_install:
    - sudo apt-add-repository -y ppa:ubuntu-sdk-team/ppa
    - sudo apt-get update
    - sudo apt-get install libgtest-dev qt5-default

before_script:
    - cmake -Dtest=ON .

script:
    - make
    - make test
